#!/usr/bin/env python3
"""Compress web/index.html into web_app.h. Run after editing the page."""

import gzip
import hashlib
from pathlib import Path

root = Path(__file__).resolve().parent.parent
html = (root / "web" / "index.html").read_bytes()
# mtime=0 keeps the output identical for identical input.
data = gzip.compress(html, compresslevel=9, mtime=0)
etag = hashlib.sha1(html).hexdigest()[:16]

rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 16]) for i in range(0, len(data), 16)]
(root / "web_app.h").write_text(
    "#pragma once\n\n"
    "// Generated by tools/build_web_app.py from web/index.html. Do not edit.\n\n"
    f'const char WEB_APP_ETAG[] = "\\"{etag}\\"";\n'
    f"const size_t WEB_APP_GZ_LEN = {len(data)};\n"
    "const uint8_t WEB_APP_GZ[] = {\n  " + ",\n  ".join(rows) + "\n};\n"
)
print(f"web_app.h: {len(html)} bytes -> {len(data)} gzipped, ETag {etag}")
